development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: meepo_dev

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: meepo_test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
