#development:
#  adapter: postgresql

#test:
#  adapter: postgresql

#production:
#  adapter: postgresql
#  url: <%#= ENV['DATABASE_URL'] %>


development:
  adapter: redis
  url: redis://localhost:6379/1
#  url: redis://red-cjotr25he99c738m019g:6379
  channel_prefix: meepo_dev

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: meepo_test

production:
  adapter: redis
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://red-cjotr25he99c738m019g:6379" } %>
  url: <%= ENV['REDIS_URL'] %>
