default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: meepo-local


#test:
#  <<: *default
#  database:


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
